import asidas from "../images/adidas.svg";
import similar1 from "../images/similar1.png";
import similar2 from "../images/similar2.png";
import similar3 from "../images/similar3.png";
import similar4 from "../images/similar4.png";
export const dummyData = [
  {
    id: 2,
    name: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    price: 9.999,
    priceBefore: 9.999,
    discount: 50,
    prand: asidas,
    productPhoto: similar1,
    rate: "4.2 of 5",
    factory: "Genena Mall",
  },
  {
    id: 3,
    name: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    price: 9.999,
    priceBefore: 9.999,
    discount: 50,
    prand: asidas,
    productPhoto: similar2,
    rate: "4.2 of 5",
    factory: "Genena Mall",
  },
  {
    id: 4,
    name: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    price: 9.999,
    priceBefore: 9.999,
    discount: 50,
    prand: asidas,
    productPhoto: similar3,
    rate: "4.2 of 5",
    factory: "Genena Mall",
  },
  {
    id: 5,
    name: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    price: 9.999,
    priceBefore: 9.999,
    discount: 50,
    prand: asidas,
    productPhoto: similar4,
    rate: "4.2 of 5",
    factory: "Genena Mall",
  },
  {
    id: 6,
    name: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    price: 9.999,
    priceBefore: 9.999,
    discount: 50,
    prand: asidas,
    productPhoto: similar1,
    rate: "4.2 of 5",
    factory: "Genena Mall",
  },
  {
    id: 7,
    name: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    price: 9.999,
    priceBefore: 9.999,
    discount: 50,
    prand: asidas,
    productPhoto: similar2,
    rate: "4.2 of 5",
    factory: "Genena Mall",
  },
  {
    id: 8,
    name: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    price: 9.999,
    priceBefore: 9.999,
    discount: 50,
    prand: asidas,
    productPhoto: similar3,
    rate: "4.2 of 5",
    factory: "Genena Mall",
  },
  {
    id: 9,
    name: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    price: 9.999,
    priceBefore: 9.999,
    discount: 50,
    prand: asidas,
    productPhoto: similar4,
    rate: "4.2 of 5",
    factory: "Genena Mall",
  },
  {
    id: 10,
    name: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    price: 9.999,
    priceBefore: 9.999,
    discount: 50,
    prand: asidas,
    productPhoto: similar1,
    rate: "4.2 of 5",
    factory: "Genena Mall",
  },
];
